<?xml version="1.0" encoding="utf-8"?><Database Name="HostelPro" Class="DataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=HostelPro;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HostelProConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.AvailibleBeds" Method="AvailibleBeds">
    <Parameter Name="DateStart" Parameter="dateStart" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DateEnd" Parameter="dateEnd" Type="System.DateTime" DbType="Date" />
    <ElementType Name="AvailibleBedsResult">
      <Column Name="RoomId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Bad Number]" Member="Bad_Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.allHostels" Method="allHostels">
    <ElementType Name="allHostelsResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ZIP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Information" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.AvailibleBeds" Method="AvailibleBeds1">
    <Parameter Name="DateStart" Parameter="dateStart" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DateEnd" Parameter="dateEnd" Type="System.DateTime" DbType="Date" />
    <ElementType Name="AvailibleBedsResult1">
      <Column Name="RoomId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BedNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>